# Multipass, Nukkit permission system
#
general:
# Messages language. Supported: eng - English, rus - Russian
# You can help translate plugin: https://crowdin.com/project/multipass/invite
  language: default
# Save translation file
  language-save: false
# Debug mode. Usually you don't need to turn it on
  debug: false
permissions:
  group:
# Default group. All new players will automagically join this group
    default-group: default
# Default priority value for groups
    default-priority: 10
# Use group name to add additional permission. If this option is enabled all
# group members will have additional permission: permission.group.<groupId>
    group-as-permission: true
  user:
# Default priority value for users
    default-priority: 100
  multiworld:
# Enable multiworld support
    enable: false
# Enable world mirroring
    mirrors:
      world: nether_world, end_world
storage:
# Database type:
# - YAML - yaml files
# - DATABASE - MySQL or SQLite. DbLib plugins is required: http://nukkit.ru/resources/dblib.14/
  type: YAML
# Auto-update interval (for multi-server system). If this values is not equal to '0'
# groups and permissions will be automatically updated.
# Time format: 1s  - 1 second, 1m - 1 minute, 1h - one hour
  auto-update-interval: '0'
  database:
# Database configuration:
# - DEFAULT - default database, configured in plugin DbLib
# - SQLITE  - custom SQLite file (filename provided below)
# - MYSQL   - custom MySQL database (configuration provided below)
    source: DEFAULT
    sqlite:
# Custom SQLite file name
      file: permissions.db
# Custom MySQL configuration
    mysql:
      host: localhost
      port: 3306
      database: database
      username: nukkit
      password: tikkun